# Generated by Django 5.1.4 on 2024-12-12 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('heart_rate', models.FloatField()),
                ('low_bp', models.FloatField()),
                ('high_bp', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('prediction_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
